CREATE TABLE llm_route_config (
    route_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_key VARCHAR2(120) NOT NULL UNIQUE,
    data_type VARCHAR2(80) NOT NULL,
    data_characteristic VARCHAR2(120) NOT NULL,
    provider VARCHAR2(40) NOT NULL,
    model_name VARCHAR2(120),
    system_prompt CLOB,
    temperature NUMBER(3,2),
    max_tokens NUMBER(10),
    priority NUMBER(5) DEFAULT 100 NOT NULL,
    enabled NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_llm_route_lookup
    ON llm_route_config (data_type, data_characteristic, enabled, priority);

CREATE TABLE llm_route_context (
    context_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id NUMBER NOT NULL,
    context_text CLOB NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_llm_context_route FOREIGN KEY (route_id) REFERENCES llm_route_config(route_id)
);

CREATE TABLE llm_training_queue (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_type VARCHAR2(80) NOT NULL,
    data_characteristic VARCHAR2(120) NOT NULL,
    route_key VARCHAR2(120),
    module_key VARCHAR2(120),
    profile_id VARCHAR2(120),
    source_type VARCHAR2(40),
    content CLOB NOT NULL,
    status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    next_run_at TIMESTAMP,
    last_error VARCHAR2(2000),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_llm_training_status CHECK (status IN ('PENDING', 'DONE', 'FAILED'))
);

CREATE INDEX idx_llm_training_status
    ON llm_training_queue (status, next_run_at, created_at);

CREATE INDEX idx_llm_training_route_key
    ON llm_training_queue (route_key);

CREATE TABLE llm_module_context (
    context_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id NUMBER NOT NULL,
    module_key VARCHAR2(120) NOT NULL,
    source_type VARCHAR2(40),
    context_text CLOB NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_llm_module_ctx_route FOREIGN KEY (route_id) REFERENCES llm_route_config(route_id)
);

CREATE INDEX idx_llm_module_ctx_lookup
    ON llm_module_context (route_id, module_key, updated_at);

CREATE TABLE llm_profile_context (
    context_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id VARCHAR2(120) NOT NULL,
    module_key VARCHAR2(120) NOT NULL,
    source_type VARCHAR2(40),
    context_text CLOB NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_llm_profile_ctx_lookup
    ON llm_profile_context (profile_id, module_key, updated_at);

CREATE TABLE llm_request_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_key VARCHAR2(120) NOT NULL,
    provider VARCHAR2(40) NOT NULL,
    model_name VARCHAR2(120) NOT NULL,
    request_summary CLOB,
    response_summary CLOB,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

INSERT INTO llm_route_config
    (route_key, data_type, data_characteristic, provider, model_name, system_prompt, temperature, max_tokens, priority, enabled)
VALUES
    ('SUPPORT_DEFAULT', 'SUPPORT', '*', 'OPENAI', 'gpt-5', 'Voce e um analista de suporte tecnico.', 0.2, 1200, 10, 1);

INSERT INTO llm_route_config
    (route_key, data_type, data_characteristic, provider, model_name, system_prompt, temperature, max_tokens, priority, enabled)
VALUES
    ('FINANCE_RISK', 'FINANCE', 'RISK', 'ANTHROPIC', 'claude-sonnet-4-5', 'Voce e um analista de risco financeiro.', 0.1, 1500, 5, 1);
